name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  uitest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [firefox, chrome, edge]

    steps:
    - uses: actions/checkout@v4

    - name: Use Webbrowser ${{ matrix.browser }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install -g selenium-side-runner
        selenium-side-runner -c "browserName=${{ matrix.browser}}" Ragaziana.side
